version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map the container port to the host port
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/blog  # Adjust as necessary
    depends_on:
      - db  # Wait for the database to be ready

  db:
    image: postgres:latest  # Use the latest version of PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    ports:
      - "5432:5432"  # Expose the database port for local access
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data
